# Generated by Django 6.0.1 on 2026-01-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('published_year', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('external_user_id', models.IntegerField(help_text='ID vindo da API de Auth')),
            ],
        ),
    ]
