# Generated by Django 6.0.1 on 2026-01-08 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('tecnico', 'Técnico'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('biografia', 'Biografia'), ('historia', 'História'), ('ciencia', 'Ciência'), ('auto_ajuda', 'Auto-ajuda'), ('poesia', 'Poesia'), ('outros', 'Outros')], default='2024-01-01', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('quero_ler', 'Quero Ler'), ('lendo', 'Lendo'), ('lido', 'Lido')], default='quero_ler', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='external_user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
