"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os                           # Adicionado para carregar variáveis de ambiente
import dj_database_url              # Adicionado para configurar o banco de dados a partir da URL
from pathlib import Path            # Adicionado para manipulação de caminhos de arquivos
from dotenv import load_dotenv      # Adicionado para carregar variáveis de ambiente de um arquivo .env

load_dotenv()                       # Carrega as variáveis de ambiente do arquivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6^t+e_%!7^dr$q0z@5k#0e6^t1^bg!g)48967@y=w-c!sv5n(_'

AUTH_API_URL = "https://usuarioapi-production.up.railway.app"


# SECURITY WARNING: don't run with debug turned on in production!
# Em produção, o DEBUG nunca deve ser True
DEBUG = False
DEV_FAKE_USER_ID = 1
DEV_FAKE_USERNAME = "Clara Maria"

# Domínio do PythonAnywhere
ALLOWED_HOSTS = ['ClaraBookShelf.pythonanywhere.com', '127.0.0.1', 'localhost'] 

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',               # Adicionado para a API REST
    'drf_spectacular',              # Adicionado para documentação da API
    'bookshelf',                    # Adicionado para o app de livros
]


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  
    ], 
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Book Shelf - Sistema de Gerenciamento de Acervos',
    'DESCRIPTION': 'O Book Shelf é uma aplicação Full Stack desenvolvida em Django para o gerenciamento de livros e e-books. O projeto utiliza uma arquitetura baseada em microsserviços e separação de responsabilidades em diferentes plataformas (PaaS).',
    'VERSION': '1.0.0',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bookshelf.middleware.JWTAuthMiddleware' 
]

JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY') # Integração real de microsserviços

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DB_URL')) 
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Caminho onde o Django procurará arquivos estáticos nos apps
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'bookshelf/static'),
]

# Arquivos de Mídia e Estáticos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Permite que o cookie de sessão seja enviado em requisições de API no mesmo domínio
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']
SESSION_COOKIE_SAMESITE = 'Lax'